class Global_Vars:
    model = []
    UNET_PATH = []
    Images = []
    Feat = []
    Target = []
    learnperc = []
    Train_Data = []
    Train_Target = []
    Test_Data = []
    Test_Target = []
    congesIndex = []
    paths = []
    Feat1 = []
    Feat2 = []
    Feat3 = []
    Tar = []